import { packageJson } from "@/lib/package";

export default function Home() {
  return (
    <main className="flex flex-col gap-4">
      <h1>Anything can be done if you have a will power!</h1>
      <p className="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur necessitatibus voluptatem neque excepturi minima ad nulla sed dolorum tenetur, corporis non ipsum. Voluptatum, consectetur ipsum! Quidem vero ipsa et incidunt nulla placeat voluptates expedita velit soluta sapiente! Sapiente omnis iste quam natus quia deleniti odit eos, corrupti hic animi et laudantium perspiciatis sint aperiam rem cupiditate aspernatur. Quia mollitia vel voluptatem amet cupiditate, eum repellat ab ipsa tempora blanditiis dicta nostrum hic delectus nulla explicabo asperiores aspernatur distinctio aperiam dignissimos atque sunt ipsam eius aut? Natusquidem in tenetur alias id? Odio eius sapiente perferendis porro accusamus.</p>
      <p className="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur necessitatibus voluptatem neque excepturi minima ad nulla sed dolorum tenetur, corporis non ipsum. Voluptatum, consectetur ipsum! Quidem vero ipsa et incidunt nulla placeat voluptates expedita velit soluta sapiente! Sapiente omnis iste quam natus quia deleniti odit eos, corrupti hic animi et laudantium perspiciatis sint aperiam rem cupiditate aspernatur. Quia mollitia vel voluptatem amet cupiditate, eum repellat ab ipsa tempora blanditiis dicta nostrum hic delectus nulla explicabo asperiores aspernatur distinctio aperiam dignissimos atque sunt ipsam eius aut? Natusquidem in tenetur alias id? Odio eius sapiente perferendis porro accusamus.</p>
      <p className="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur necessitatibus voluptatem neque excepturi minima ad nulla sed dolorum tenetur, corporis non ipsum. Voluptatum, consectetur ipsum! Quidem vero ipsa et incidunt nulla placeat voluptates expedita velit soluta sapiente! Sapiente omnis iste quam natus quia deleniti odit eos, corrupti hic animi et laudantium perspiciatis sint aperiam rem cupiditate aspernatur. Quia mollitia vel voluptatem amet cupiditate, eum repellat ab ipsa tempora blanditiis dicta nostrum hic delectus nulla explicabo asperiores aspernatur distinctio aperiam dignissimos atque sunt ipsam eius aut? Natusquidem in tenetur alias id? Odio eius sapiente perferendis porro accusamus.</p>
      <p className="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur necessitatibus voluptatem neque excepturi minima ad nulla sed dolorum tenetur, corporis non ipsum. Voluptatum, consectetur ipsum! Quidem vero ipsa et incidunt nulla placeat voluptates expedita velit soluta sapiente! Sapiente omnis iste quam natus quia deleniti odit eos, corrupti hic animi et laudantium perspiciatis sint aperiam rem cupiditate aspernatur. Quia mollitia vel voluptatem amet cupiditate, eum repellat ab ipsa tempora blanditiis dicta nostrum hic delectus nulla explicabo asperiores aspernatur distinctio aperiam dignissimos atque sunt ipsam eius aut? Natusquidem in tenetur alias id? Odio eius sapiente perferendis porro accusamus.</p>
      <p className="text-justify">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aspernatur necessitatibus voluptatem neque excepturi minima ad nulla sed dolorum tenetur, corporis non ipsum. Voluptatum, consectetur ipsum! Quidem vero ipsa et incidunt nulla placeat voluptates expedita velit soluta sapiente! Sapiente omnis iste quam natus quia deleniti odit eos, corrupti hic animi et laudantium perspiciatis sint aperiam rem cupiditate aspernatur. Quia mollitia vel voluptatem amet cupiditate, eum repellat ab ipsa tempora blanditiis dicta nostrum hic delectus nulla explicabo asperiores aspernatur distinctio aperiam dignissimos atque sunt ipsam eius aut? Natusquidem in tenetur alias id? Odio eius sapiente perferendis porro accusamus.</p>
    </main>
  );
}
